/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Current User */
    get: operations["read_current_user_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/articles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Articles */
    get: operations["get_articles_api_v1_articles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/articles/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Article */
    get: operations["get_article_api_v1_articles__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/articles/{article_id}/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Send Feedback */
    put: operations["send_feedback_api_v1_articles__article_id__feedback_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account-unlocks/request-code": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Unlock Request */
    post: operations["create_unlock_request_api_v1_account_unlocks_request_code_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/account-unlocks/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify Unlock Request */
    post: operations["verify_unlock_request_api_v1_account_unlocks_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Tickets */
    get: operations["get_tickets_api_v1_tickets_get"];
    put?: never;
    /** Open Ticket */
    post: operations["open_ticket_api_v1_tickets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tickets/{ticket_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Ticket */
    get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tickets/{ticket_id}/assignment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Assignment */
    patch: operations["patch_assignment_api_v1_tickets__ticket_id__assignment_patch"];
    trace?: never;
  };
  "/api/v1/tickets/{ticket_id}/priority": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Priority */
    patch: operations["patch_priority_api_v1_tickets__ticket_id__priority_patch"];
    trace?: never;
  };
  "/api/v1/tickets/{ticket_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Status */
    patch: operations["patch_status_api_v1_tickets__ticket_id__status_patch"];
    trace?: never;
  };
  "/api/v1/dashboard/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Summary */
    get: operations["get_summary_api_v1_dashboard_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ArticleCategory
     * @enum {string}
     */
    ArticleCategory:
      "ACCESS" | "SOFTWARE" | "NETWORK" | "HARDWARE" | "SECURITY";
    /** ArticleDetail */
    ArticleDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Slug */
      slug: string;
      /** Summary */
      summary: string;
      category: components["schemas"]["ArticleCategory"];
      /** Content */
      content: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ArticleFeedbackRequest */
    ArticleFeedbackRequest: {
      /** Resolved */
      resolved: boolean;
    };
    /** ArticleFeedbackResponse */
    ArticleFeedbackResponse: {
      /**
       * Article Id
       * Format: uuid
       */
      article_id: string;
      /** Resolved */
      resolved: boolean;
    };
    /** ArticleSummary */
    ArticleSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /** Slug */
      slug: string;
      /** Summary */
      summary: string;
      category: components["schemas"]["ArticleCategory"];
    };
    /** DashboardEmployeeSummary */
    DashboardEmployeeSummary: {
      /** Account Locked */
      account_locked: boolean;
      /** Open Tickets */
      open_tickets: number;
      /** In Progress Tickets */
      in_progress_tickets: number;
      /** Resolved Tickets */
      resolved_tickets: number;
    };
    /** DashboardTechnicianSummary */
    DashboardTechnicianSummary: {
      /** Unassigned Tickets */
      unassigned_tickets: number;
      /** By Status */
      by_status: {
        [key: string]: number;
      };
      /** By Priority */
      by_priority: {
        [key: string]: number;
      };
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @example thiago@example.test
       */
      email: string;
      /** Password */
      password: string;
    };
    /** TicketAssignmentUpdate */
    TicketAssignmentUpdate: {
      /**
       * Assignee Id
       * Format: uuid
       */
      assignee_id: string;
    };
    /**
     * TicketCategory
     * @enum {string}
     */
    TicketCategory:
      "ACCESS" | "SOFTWARE" | "NETWORK" | "HARDWARE" | "SECURITY" | "OTHER";
    /** TicketCreate */
    TicketCreate: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      category: components["schemas"]["TicketCategory"];
    };
    /** TicketDetail */
    TicketDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Protocol */
      protocol: string;
      /** Title */
      title: string;
      category: components["schemas"]["TicketCategory"];
      priority: components["schemas"]["TicketPriority"];
      status: components["schemas"]["TicketStatus"];
      requester: components["schemas"]["UserRef"];
      assignee: components["schemas"]["UserRef"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Resolved At */
      resolved_at: string | null;
      /** Description */
      description: string;
      /** Events */
      events?: components["schemas"]["TicketEventRead"][];
    };
    /** TicketEventRead */
    TicketEventRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Author Id
       * Format: uuid
       */
      author_id: string;
      author: components["schemas"]["UserRef"];
      from_status: components["schemas"]["TicketStatus"] | null;
      to_status: components["schemas"]["TicketStatus"];
      /** Comment */
      comment: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * TicketPriority
     * @enum {string}
     */
    TicketPriority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    /** TicketPriorityUpdate */
    TicketPriorityUpdate: {
      priority: components["schemas"]["TicketPriority"];
    };
    /**
     * TicketStatus
     * @enum {string}
     */
    TicketStatus: "OPEN" | "TRIAGE" | "IN_PROGRESS" | "RESOLVED";
    /** TicketStatusUpdate */
    TicketStatusUpdate: {
      status: components["schemas"]["TicketStatus"];
      /** Comment */
      comment?: string | null;
    };
    /** TicketSummary */
    TicketSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Protocol */
      protocol: string;
      /** Title */
      title: string;
      category: components["schemas"]["TicketCategory"];
      priority: components["schemas"]["TicketPriority"];
      status: components["schemas"]["TicketStatus"];
      requester: components["schemas"]["UserRef"];
      assignee: components["schemas"]["UserRef"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Resolved At */
      resolved_at: string | null;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /** Expires In */
      expires_in: number;
    };
    /** UnlockRequestResponse */
    UnlockRequestResponse: {
      /**
       * Challenge Id
       * Format: uuid
       */
      challenge_id: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Demo Code */
      demo_code?: string | null;
    };
    /** UnlockVerifyRequest */
    UnlockVerifyRequest: {
      /**
       * Challenge Id
       * Format: uuid
       */
      challenge_id: string;
      /** Code */
      code: string;
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Email */
      email: string;
      role: components["schemas"]["UserRole"];
      /** Account Locked */
      account_locked: boolean;
    };
    /** UserRef */
    UserRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "EMPLOYEE" | "TECHNICIAN";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_current_user_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
    };
  };
  get_articles_api_v1_articles_get: {
    parameters: {
      query?: {
        q?: string | null;
        category?: components["schemas"]["ArticleCategory"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_article_api_v1_articles__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_feedback_api_v1_articles__article_id__feedback_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        article_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleFeedbackRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleFeedbackResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_unlock_request_api_v1_account_unlocks_request_code_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnlockRequestResponse"];
        };
      };
    };
  };
  verify_unlock_request_api_v1_account_unlocks_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UnlockVerifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_tickets_api_v1_tickets_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["TicketStatus"] | null;
        priority?: components["schemas"]["TicketPriority"] | null;
        category?: components["schemas"]["TicketCategory"] | null;
        assignee_id?: string | null;
        unassigned?: boolean;
        /** @deprecated */
        status_filter?: components["schemas"]["TicketStatus"] | null;
        /** @deprecated */
        priority_filter?: components["schemas"]["TicketPriority"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  open_ticket_api_v1_tickets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ticket_api_v1_tickets__ticket_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_assignment_api_v1_tickets__ticket_id__assignment_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketAssignmentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_priority_api_v1_tickets__ticket_id__priority_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketPriorityUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_status_api_v1_tickets__ticket_id__status_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TicketStatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_summary_api_v1_dashboard_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["DashboardEmployeeSummary"]
            | components["schemas"]["DashboardTechnicianSummary"];
        };
      };
    };
  };
}
